swagger: '2.0'
info:
  title: readme
  description: |
    <h1>inject<br><marquee>html</marquee>
    <a href=#>click me!</a></h1>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
